// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `app.bsky.contact.defs` namespace.
///Associates a profile with the positional index of the contact import input in the call to `app.bsky.contact.importContacts`, so clients can know which phone caused a particular match.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct MatchAndContactIndexData {
    ///The index of this match in the import contact input.
    pub contact_index: crate::types::LimitedU16<999u16>,
    ///Profile of the matched user.
    pub r#match: crate::app::bsky::actor::defs::ProfileView,
}
pub type MatchAndContactIndex = crate::types::Object<MatchAndContactIndexData>;
///A stash object to be sent via bsync representing a notification to be created.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct NotificationData {
    ///The DID of who this notification comes from.
    pub from: crate::types::string::Did,
    ///The DID of who this notification should go to.
    pub to: crate::types::string::Did,
}
pub type Notification = crate::types::Object<NotificationData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct SyncStatusData {
    ///Number of existing contact matches resulting of the user imports and of their imported contacts having imported the user. Matches stop being counted when the user either follows the matched contact or dismisses the match.
    pub matches_count: usize,
    ///Last date when contacts where imported.
    pub synced_at: crate::types::string::Datetime,
}
pub type SyncStatus = crate::types::Object<SyncStatusData>;
