// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `chat.bsky.actor.getStatus` namespace.
pub const NSID: &str = "chat.bsky.actor.getStatus";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Whether the viewer's account is allowed to create group chats. New accounts are restricted from creating groups.
    pub can_create_groups: bool,
    ///True when the viewer's account is disabled and cannot actively participate in chat.
    pub chat_disabled: bool,
    ///The maximum number of members allowed in a group conversation.
    pub group_member_limit: i64,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
