// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `app.bsky.video.abortUpload` namespace.
pub const NSID: &str = "app.bsky.video.abortUpload";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    pub job_id: String,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Present only when state is completed.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub completed_job_id: core::option::Option<String>,
    ///Present only when state is failed.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub failure_reason: core::option::Option<String>,
    pub state: String,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///The job ID is unknown or aged out of retention; known terminal sessions return their outcome and are never reported as not found.
    UploadNotFound(Option<String>),
    ///A finish is in progress; check getUploadStatus and retry.
    UploadNotReady(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::UploadNotFound(msg) => {
                write!(_f, "UploadNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::UploadNotReady(msg) => {
                write!(_f, "UploadNotReady")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
