// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.moderation.cancelScheduledActions` namespace.
pub const NSID: &str = "tools.ozone.moderation.cancelScheduledActions";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///Optional comment describing the reason for cancellation
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub comment: core::option::Option<String>,
    ///Array of DID subjects to cancel scheduled actions for
    pub subjects: Vec<crate::types::string::Did>,
}
pub type Input = crate::types::Object<InputData>;
pub type Output = CancellationResults;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct CancellationResultsData {
    ///DIDs for which cancellation failed with error details
    pub failed: Vec<FailedCancellation>,
    ///DIDs for which all pending scheduled actions were successfully cancelled
    pub succeeded: Vec<crate::types::string::Did>,
}
pub type CancellationResults = crate::types::Object<CancellationResultsData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct FailedCancellationData {
    pub did: crate::types::string::Did,
    pub error: String,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub error_code: core::option::Option<String>,
}
pub type FailedCancellation = crate::types::Object<FailedCancellationData>;
