// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.moderation.listScheduledActions` namespace.
pub const NSID: &str = "tools.ozone.moderation.listScheduledActions";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///Cursor for pagination
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cursor: core::option::Option<String>,
    ///Filter actions scheduled to execute before this time
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub ends_before: core::option::Option<crate::types::string::Datetime>,
    ///Maximum number of results to return
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub limit: core::option::Option<crate::types::LimitedNonZeroU8<100u8>>,
    ///Filter actions scheduled to execute after this time
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub starts_after: core::option::Option<crate::types::string::Datetime>,
    ///Filter actions by status
    pub statuses: Vec<String>,
    ///Filter actions for specific DID subjects
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub subjects: core::option::Option<Vec<crate::types::string::Did>>,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    pub actions: Vec<crate::tools::ozone::moderation::defs::ScheduledActionView>,
    ///Cursor for next page of results
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cursor: core::option::Option<String>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
