//! Fidelity tests for the code generated by `lexgen`.
//!
//! These guard that the generated structs faithfully represent the source
//! lexicons, exercising the public API exactly as a downstream consumer would.
//! Each case asserts three invariants against a lexicon-shaped JSON payload:
//!
//! 1. **Typed coverage** — every field in the payload is reachable as a typed
//!    struct field (not just preserved as opaque data).
//! 2. **No leakage** — `Object::extra_data` stays empty, proving the struct
//!    fully models the payload rather than catching unknown fields. This is the
//!    assertion that catches a regen silently dropping a field: a dropped field
//!    falls through to `extra_data` instead of failing to compile.
//! 3. **Round-trip stability** — re-serializing yields the original JSON, so no
//!    field is lost or renamed on the way out.
//!
//! Invariant 2 is the important one: round-trip alone is not enough, because
//! `extra_data` round-trips unknown fields too. A field is only proven *typed*
//! when it is both reachable as a struct field and absent from `extra_data`.

/// Asserts that an `Object`'s `extra_data` caught nothing, i.e. every field in
/// the payload was modelled by a typed field.
#[cfg(any(
    feature = "namespace-appbsky",
    feature = "namespace-chatbsky",
    feature = "namespace-toolsozone"
))]
fn assert_fully_typed(extra_data: &impl serde::Serialize, what: &str) {
    let extra = serde_json::to_value(extra_data).expect("serialize extra_data");
    assert_eq!(extra, serde_json::json!({}), "{what}: fields leaked into extra_data: {extra}");
}

#[cfg(feature = "namespace-chatbsky")]
mod chat {
    use super::assert_fully_typed;
    use atrium_api::chat::bsky::convo::defs::{MessageInput, MessageView, MessageViewReplyToRefs};
    use atrium_api::types::Union;
    use serde_json::{Value, from_str, from_value, to_value};

    /// `chat.bsky.convo.defs#messageView` gained `replyTo`, a union that embeds
    /// the replied-to message inline. This proves the field is typed, that the
    /// recursive `#messageView` union variant resolves (rather than falling into
    /// `Union::Unknown`), and that nothing leaks to `extra_data` at either level.
    #[test]
    fn message_view_reply_to_is_typed_and_recursive() {
        const JSON: &str = r#"{
            "id": "msg-2",
            "rev": "rev-2",
            "text": "a reply",
            "sender": { "did": "did:plc:z72i7hdynmk6r22z27h6tvur" },
            "sentAt": "2026-06-21T12:00:00.000Z",
            "replyTo": {
                "$type": "chat.bsky.convo.defs#messageView",
                "id": "msg-1",
                "rev": "rev-1",
                "text": "the original",
                "sender": { "did": "did:plc:ewvi7nxzyoun6zhxrhs64oiz" },
                "sentAt": "2026-06-21T11:59:00.000Z"
            }
        }"#;

        let value: Value = from_str(JSON).expect("valid JSON");
        let view: MessageView = from_value(value.clone()).expect("deserialize messageView");

        // Invariant 1 + the recursive union variant resolves to a typed message.
        match view.reply_to.as_ref().expect("replyTo is present") {
            Union::Refs(MessageViewReplyToRefs::MessageView(original)) => {
                assert_eq!(original.id, "msg-1");
                assert_eq!(original.text, "the original");
                // Per the lexicon, the embedded message is not itself populated
                // with a replyTo (only a single level is embedded).
                assert!(original.reply_to.is_none());
                // Invariant 2, nested.
                assert_fully_typed(&original.extra_data, "embedded messageView");
            }
            other => panic!("replyTo did not resolve to a typed messageView: {other:?}"),
        }

        // Invariant 2, top level.
        assert_fully_typed(&view.extra_data, "messageView");

        // Invariant 3.
        assert_eq!(to_value(&view).expect("re-serialize"), value, "round-trip changed the payload");
    }

    /// `chat.bsky.convo.defs#messageInput` gained `replyTo` as a `#replyRef`
    /// (a bare `messageId`). This is what a client sets when sending a reply.
    #[test]
    fn message_input_reply_to_is_typed() {
        const JSON: &str = r#"{
            "text": "a reply",
            "replyTo": { "messageId": "msg-1" }
        }"#;

        let value: Value = from_str(JSON).expect("valid JSON");
        let input: MessageInput = from_value(value.clone()).expect("deserialize messageInput");

        let reply_to = input.reply_to.as_ref().expect("replyTo is present");
        assert_eq!(reply_to.message_id, "msg-1");
        assert_fully_typed(&reply_to.extra_data, "replyRef");
        assert_fully_typed(&input.extra_data, "messageInput");

        assert_eq!(
            to_value(&input).expect("re-serialize"),
            value,
            "round-trip changed the payload"
        );
    }
}

#[cfg(feature = "namespace-toolsozone")]
mod ozone {
    use super::assert_fully_typed;
    use atrium_api::tools::ozone::report::query_activities::{Output, Parameters};
    use serde_json::{Value, from_str, from_value, to_value};

    /// The new `tools.ozone.report.queryActivities` endpoint: confirm its
    /// parameters map every camelCase lexicon field to a typed field (including
    /// the bounded `limit`) with nothing left in `extra_data`.
    #[test]
    fn query_activities_parameters_round_trip() {
        const JSON: &str = r#"{
            "activityTypes": ["closeActivity", "escalationActivity"],
            "createdAfter": "2026-01-01T00:00:00.000Z",
            "createdBefore": "2026-06-21T00:00:00.000Z",
            "sortDirection": "asc",
            "limit": 50,
            "cursor": "1700000000000::abc"
        }"#;

        let value: Value = from_str(JSON).expect("valid JSON");
        let params: Parameters = from_value(value.clone()).expect("deserialize parameters");

        assert_eq!(
            params.activity_types.as_deref(),
            Some(["closeActivity".to_string(), "escalationActivity".to_string()].as_slice())
        );
        assert!(params.created_after.is_some());
        assert!(params.limit.is_some());
        assert_eq!(params.cursor.as_deref(), Some("1700000000000::abc"));
        assert_fully_typed(&params.extra_data, "queryActivities parameters");

        assert_eq!(
            to_value(&params).expect("re-serialize"),
            value,
            "round-trip changed the payload"
        );
    }

    /// The endpoint output carries the activity list and an optional cursor.
    #[test]
    fn query_activities_output_round_trip() {
        const JSON: &str = r#"{ "activities": [], "cursor": "next" }"#;

        let value: Value = from_str(JSON).expect("valid JSON");
        let output: Output = from_value(value.clone()).expect("deserialize output");

        assert!(output.activities.is_empty());
        assert_eq!(output.cursor.as_deref(), Some("next"));
        assert_fully_typed(&output.extra_data, "queryActivities output");

        assert_eq!(
            to_value(&output).expect("re-serialize"),
            value,
            "round-trip changed the payload"
        );
    }
}

#[cfg(feature = "namespace-appbsky")]
mod actor {
    use super::assert_fully_typed;
    use atrium_api::app::bsky::actor::ContentVisibilityDeclaration;
    use atrium_api::record::KnownRecord;
    use atrium_api::types::Collection;
    use serde_json::{Value, from_str, from_value, json, to_value};

    /// `app.bsky.actor.contentVisibilityDeclaration` is the first record whose
    /// NSID leaf is camelCase, and it broke an assumption in codegen: the NSID
    /// was rebuilt from the snake_case'd file stem, so the record never matched
    /// its own schema and got no `Collection` impl. `KnownRecord` is built from
    /// schema ids, so it *did* gain the variant — leaving downstream crates with
    /// an arm they could not satisfy (fixed upstream in atrium-rs/atrium#345).
    ///
    /// Naming the record through the associated type makes this fail to compile
    /// if the `Collection` impl disappears again; the assertions catch the two
    /// halves disagreeing on the NSID or the record type.
    #[test]
    fn content_visibility_declaration_collection_matches_known_record() {
        const NSID: &str = "app.bsky.actor.contentVisibilityDeclaration";
        const JSON: &str = r#"{ "hideFromAlgorithmicRecommendations": true }"#;

        // The `Collection` impl exists and carries the camelCase NSID verbatim,
        // rather than a snake_case'd or otherwise mangled form.
        assert_eq!(ContentVisibilityDeclaration::NSID, NSID);
        assert_eq!(ContentVisibilityDeclaration::nsid().as_str(), NSID);

        let value: Value = from_str(JSON).expect("valid JSON");
        let record: <ContentVisibilityDeclaration as Collection>::Record =
            from_value(value.clone()).expect("deserialize record");

        assert!(record.hide_from_algorithmic_recommendations);
        assert_fully_typed(&record.extra_data, "contentVisibilityDeclaration record");
        assert_eq!(
            to_value(&record).expect("re-serialize"),
            value,
            "round-trip changed the payload"
        );

        // The `$type`-tagged form resolves to the matching `KnownRecord` variant
        // holding the very same record type the `Collection` impl points at.
        let mut tagged = value;
        tagged.as_object_mut().expect("object").insert("$type".into(), json!(NSID));

        match from_value::<KnownRecord>(tagged).expect("deserialize KnownRecord") {
            KnownRecord::AppBskyActorContentVisibilityDeclaration(boxed) => {
                assert_eq!(*boxed, record, "KnownRecord and Collection disagree on the record");
            }
            other => panic!("`{NSID}` resolved to the wrong KnownRecord variant: {other:?}"),
        }
    }
}
