// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.queue.assignModerator` namespace.
pub const NSID: &str = "tools.ozone.queue.assignModerator";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///DID to be assigned.
    pub did: String,
    ///The ID of the queue to assign the user to.
    pub queue_id: i64,
}
pub type Input = crate::types::Object<InputData>;
pub type Output = crate::tools::ozone::queue::defs::AssignmentView;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///The specified queue does not exist or is not enabled.
    InvalidAssignment(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::InvalidAssignment(msg) => {
                write!(_f, "InvalidAssignment")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
