// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.queue.createQueue` namespace.
pub const NSID: &str = "tools.ozone.queue.createQueue";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///Collection name for record subjects. Required if subjectTypes includes 'record'.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub collection: core::option::Option<crate::types::string::Nsid>,
    ///Optional description of the queue
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub description: core::option::Option<String>,
    ///Display name for the queue (must be unique)
    pub name: String,
    ///Policy keys to recommend when actioning reports in this queue
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub recommended_policies: core::option::Option<Vec<String>>,
    ///Report reason types (fully qualified NSIDs)
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub report_types: core::option::Option<Vec<String>>,
    ///Subject types this queue accepts
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub subject_types: core::option::Option<Vec<String>>,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    pub queue: crate::tools::ozone::queue::defs::QueueView,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///One or more recommended policy keys do not exist in the configured policy list
    InvalidRecommendedPolicies(Option<String>),
    ///The queue configuration conflicts with an existing queue
    ConflictingQueue(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::InvalidRecommendedPolicies(msg) => {
                write!(_f, "InvalidRecommendedPolicies")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::ConflictingQueue(msg) => {
                write!(_f, "ConflictingQueue")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
