// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.queue.defs` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct AssignmentViewData {
    pub did: crate::types::string::Did,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub end_at: core::option::Option<crate::types::string::Datetime>,
    pub id: i64,
    ///The moderator assigned to this queue
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub moderator: core::option::Option<crate::tools::ozone::team::defs::Member>,
    pub queue: QueueView,
    pub start_at: crate::types::string::Datetime,
}
pub type AssignmentView = crate::types::Object<AssignmentViewData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct QueueStatsData {
    ///Percentage of reports actioned (actionedCount / inboundCount * 100), rounded to nearest integer. Absent when inboundCount is 0.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub action_rate: core::option::Option<i64>,
    ///Number of reports in 'closed' status
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub actioned_count: core::option::Option<i64>,
    ///Average time in seconds from report creation to close, for reports closed in this period.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub avg_handling_time_sec: core::option::Option<i64>,
    ///Number of reports in 'escalated' status
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub escalated_count: core::option::Option<i64>,
    ///Reports received in this queue in the last 24 hours.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub inbound_count: core::option::Option<i64>,
    ///When these statistics were last computed
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub last_updated: core::option::Option<crate::types::string::Datetime>,
    ///Number of reports in 'open' status
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub pending_count: core::option::Option<i64>,
}
pub type QueueStats = crate::types::Object<QueueStatsData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct QueueViewData {
    ///Collection name for record subjects (e.g., 'app.bsky.feed.post')
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub collection: core::option::Option<crate::types::string::Nsid>,
    pub created_at: crate::types::string::Datetime,
    ///DID of moderator who created this queue
    pub created_by: crate::types::string::Did,
    ///When the queue was deleted, if applicable
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub deleted_at: core::option::Option<crate::types::string::Datetime>,
    ///Optional description of the queue
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub description: core::option::Option<String>,
    ///Whether this queue is currently active
    pub enabled: bool,
    ///Queue ID
    pub id: i64,
    ///Display name of the queue
    pub name: String,
    ///Policy keys recommended when actioning reports in this queue
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub recommended_policies: core::option::Option<Vec<String>>,
    ///Report reason types this queue accepts (fully qualified NSIDs)
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub report_types: core::option::Option<Vec<String>>,
    ///Statistics about this queue
    pub stats: QueueStats,
    ///Subject types this queue accepts.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub subject_types: core::option::Option<Vec<String>>,
    pub updated_at: crate::types::string::Datetime,
}
pub type QueueView = crate::types::Object<QueueViewData>;
