// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.queue.deleteQueue` namespace.
pub const NSID: &str = "tools.ozone.queue.deleteQueue";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///Optional: migrate all reports to this queue. If not specified, reports will be set to unassigned (-1).
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub migrate_to_queue_id: core::option::Option<i64>,
    ///ID of the queue to delete
    pub queue_id: i64,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    pub deleted: bool,
    ///Number of reports that were migrated (if migration occurred)
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub reports_migrated: core::option::Option<i64>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
