// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.queue.listQueues` namespace.
pub const NSID: &str = "tools.ozone.queue.listQueues";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///Filter queues by collection name (e.g. 'app.bsky.feed.post').
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub collection: core::option::Option<String>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cursor: core::option::Option<String>,
    ///Filter by enabled status. If not specified, returns all queues.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub enabled: core::option::Option<bool>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub limit: core::option::Option<crate::types::LimitedNonZeroU8<100u8>>,
    ///Filter queues that handle any of these report reason types.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub report_types: core::option::Option<Vec<String>>,
    ///Filter queues that handle this subject type ('account' or 'record').
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub subject_type: core::option::Option<String>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cursor: core::option::Option<String>,
    pub queues: Vec<crate::tools::ozone::queue::defs::QueueView>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
