// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.queue.routeReports` namespace.
pub const NSID: &str = "tools.ozone.queue.routeReports";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///End of report ID range (inclusive). Difference between start and end must be less than 5,000.
    pub end_report_id: i64,
    ///Start of report ID range (inclusive).
    pub start_report_id: i64,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///The number of reports assigned to a queue.
    pub assigned: i64,
    ///The number of reports with no matching queue.
    pub unmatched: i64,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///The request is invalid, such as missing required fields or invalid field values.
    OutOfRange(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::OutOfRange(msg) => {
                write!(_f, "OutOfRange")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
