// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `chat.bsky.group` namespace.
pub mod add_members;
pub mod approve_join_request;
pub mod create_group;
pub mod create_join_link;
pub mod defs;
pub mod disable_join_link;
pub mod edit_group;
pub mod edit_join_link;
pub mod enable_join_link;
pub mod get_join_link_previews;
pub mod list_join_requests;
pub mod list_mutual_groups;
pub mod reject_join_request;
pub mod remove_members;
pub mod request_join;
pub mod update_join_requests_read;
pub mod withdraw_join_request;
