// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.report.closeReports` namespace.
pub const NSID: &str = "tools.ozone.report.closeReports";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///Optional moderator-only note recorded on each close activity. Not visible to reporters.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub internal_note: core::option::Option<String>,
    ///Set true when this action is triggered by an automated process. Defaults to false.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub is_automated: core::option::Option<bool>,
    ///If specified, only reports of the given report types (fully qualified reason NSIDs) are closed. When omitted, all non-closed reports on the subject are targeted.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub report_types: core::option::Option<Vec<String>>,
    ///Subject DID (account-level reports) or AT-URI (record-level reports) whose reports should be closed.
    pub subject: String,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Number of reports that were transitioned to closed.
    pub closed_count: i64,
    ///IDs of the reports that were closed.
    pub report_ids: Vec<i64>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
