// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.report.getLiveStats` namespace.
pub const NSID: &str = "tools.ozone.report.getLiveStats";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///Filter stats by moderator DID.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub moderator_did: core::option::Option<crate::types::string::Did>,
    ///Filter stats by queue. Use -1 for unqueued reports.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub queue_id: core::option::Option<i64>,
    ///Filter stats by report types.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub report_types: core::option::Option<Vec<String>>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Statistics for the requested filter.
    pub stats: crate::tools::ozone::report::defs::LiveStats,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
