// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.report.getAssignments` namespace.
pub const NSID: &str = "tools.ozone.report.getAssignments";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cursor: core::option::Option<String>,
    ///If specified, returns assignments for these moderators only.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub dids: core::option::Option<Vec<crate::types::string::Did>>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub limit: core::option::Option<crate::types::LimitedNonZeroU8<100u8>>,
    ///When true, only returns active assignments.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub only_active: core::option::Option<bool>,
    ///If specified, returns assignments for these reports only.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub report_ids: core::option::Option<Vec<i64>>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    pub assignments: Vec<crate::tools::ozone::report::defs::AssignmentView>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cursor: core::option::Option<String>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
