// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.report.queryReports` namespace.
pub const NSID: &str = "tools.ozone.report.queryReports";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///Filter by the DID of the moderator permanently assigned to the report.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub assigned_to: core::option::Option<crate::types::string::Did>,
    ///If specified, reports where the subject belongs to the given collections will be returned. When subjectType is set to 'account', this will be ignored.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub collections: core::option::Option<Vec<crate::types::string::Nsid>>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cursor: core::option::Option<String>,
    ///Filter to reports where the subject is this DID or any record owned by this DID. Unlike `subject` (which scopes to a specific account or record), this returns all reports tied to the DID across both account-level and record-level subjects.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub did: core::option::Option<crate::types::string::Did>,
    ///Filter by muted status. true returns only muted reports, false returns only unmuted reports. Defaults to false.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub is_muted: core::option::Option<bool>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub limit: core::option::Option<crate::types::LimitedNonZeroU8<100u8>>,
    ///Filter by queue ID. Use -1 for unassigned reports.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub queue_id: core::option::Option<i64>,
    ///Filter by report types (fully qualified string in the format of com.atproto.moderation.defs#reason<name>).
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub report_types: core::option::Option<Vec<String>>,
    ///Retrieve reports created after a given timestamp
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub reported_after: core::option::Option<crate::types::string::Datetime>,
    ///Retrieve reports created before a given timestamp
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub reported_before: core::option::Option<crate::types::string::Datetime>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub sort_direction: core::option::Option<String>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub sort_field: core::option::Option<String>,
    ///Filter by report status.
    pub status: String,
    ///Filter by subject DID or AT-URI.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub subject: core::option::Option<String>,
    ///If specified, reports of the given type (account or record) will be returned.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub subject_type: core::option::Option<String>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cursor: core::option::Option<String>,
    pub reports: Vec<crate::tools::ozone::report::defs::ReportView>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
