// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.report.queryActivities` namespace.
pub const NSID: &str = "tools.ozone.report.queryActivities";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///Filter to specific activity types (e.g. closeActivity, escalationActivity). If omitted, all types are returned.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub activity_types: core::option::Option<Vec<String>>,
    ///Retrieve activities created at or after a given timestamp
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub created_after: core::option::Option<crate::types::string::Datetime>,
    ///Retrieve activities created at or before a given timestamp
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub created_before: core::option::Option<crate::types::string::Datetime>,
    ///Cursor of the form `<createdAtMs>::<activityId>`.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cursor: core::option::Option<String>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub limit: core::option::Option<crate::types::LimitedNonZeroU8<100u8>>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub sort_direction: core::option::Option<String>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    pub activities: Vec<crate::tools::ozone::report::defs::ReportActivityView>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cursor: core::option::Option<String>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
