// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.report.unassignModerator` namespace.
pub const NSID: &str = "tools.ozone.report.unassignModerator";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///The ID of the report to unassign.
    pub report_id: i64,
}
pub type Input = crate::types::Object<InputData>;
pub type Output = crate::tools::ozone::report::defs::AssignmentView;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///The report ID is invalid.
    InvalidAssignment(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::InvalidAssignment(msg) => {
                write!(_f, "InvalidAssignment")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
