// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `app.bsky.actor.contentVisibilityDeclaration` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    ///Whether the account requests that its posts be hidden from algorithmic recommendations. Consumers must treat a missing record as false.
    pub hide_from_algorithmic_recommendations: bool,
}
pub type Record = crate::types::Object<RecordData>;
