// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.queue` namespace.
pub mod assign_moderator;
pub mod create_queue;
pub mod defs;
pub mod delete_queue;
pub mod get_assignments;
pub mod list_queues;
pub mod route_reports;
pub mod unassign_moderator;
pub mod update_queue;
