// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.report` namespace.
pub mod assign_moderator;
pub mod close_reports;
pub mod create_activity;
pub mod defs;
pub mod get_assignments;
pub mod get_historical_stats;
pub mod get_latest_report;
pub mod get_live_stats;
pub mod get_report;
pub mod list_activities;
pub mod query_activities;
pub mod query_reports;
pub mod reassign_queue;
pub mod refresh_stats;
pub mod unassign_moderator;
