// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `chat.bsky.group.createJoinLink` namespace.
pub const NSID: &str = "chat.bsky.group.createJoinLink";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    pub convo_id: String,
    pub join_rule: crate::chat::bsky::group::defs::JoinRule,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub require_approval: core::option::Option<bool>,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    pub join_link: crate::chat::bsky::group::defs::JoinLinkView,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    EnabledJoinLinkAlreadyExists(Option<String>),
    InvalidConvo(Option<String>),
    InsufficientRole(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::EnabledJoinLinkAlreadyExists(msg) => {
                write!(_f, "EnabledJoinLinkAlreadyExists")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::InvalidConvo(msg) => {
                write!(_f, "InvalidConvo")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::InsufficientRole(msg) => {
                write!(_f, "InsufficientRole")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
