// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `chat.bsky.group.getJoinLinkPreviews` namespace.
pub const NSID: &str = "chat.bsky.group.getJoinLinkPreviews";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    pub codes: Vec<String>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    pub join_link_previews: Vec<crate::types::Union<OutputJoinLinkPreviewsItem>>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum OutputJoinLinkPreviewsItem {
    #[serde(rename = "chat.bsky.group.defs#joinLinkPreviewView")]
    ChatBskyGroupDefsJoinLinkPreviewView(
        Box<crate::chat::bsky::group::defs::JoinLinkPreviewView>,
    ),
    #[serde(rename = "chat.bsky.group.defs#disabledJoinLinkPreviewView")]
    ChatBskyGroupDefsDisabledJoinLinkPreviewView(
        Box<crate::chat::bsky::group::defs::DisabledJoinLinkPreviewView>,
    ),
    #[serde(rename = "chat.bsky.group.defs#invalidJoinLinkPreviewView")]
    ChatBskyGroupDefsInvalidJoinLinkPreviewView(
        Box<crate::chat::bsky::group::defs::InvalidJoinLinkPreviewView>,
    ),
}
