// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `chat.bsky.notification.defs` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ChatPreferenceData {
    pub include: String,
    pub push: bool,
}
pub type ChatPreference = crate::types::Object<ChatPreferenceData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PreferencesData {
    pub chat: ChatPreference,
    pub chat_request: ChatPreference,
}
pub type Preferences = crate::types::Object<PreferencesData>;
