// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `chat.bsky.notification.putPreferences` namespace.
pub const NSID: &str = "chat.bsky.notification.putPreferences";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub chat: core::option::Option<
        crate::chat::bsky::notification::defs::ChatPreference,
    >,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub chat_request: core::option::Option<
        crate::chat::bsky::notification::defs::ChatPreference,
    >,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    pub preferences: crate::chat::bsky::notification::defs::Preferences,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
