// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `chat.bsky.convo.getMessages` namespace.
pub const NSID: &str = "chat.bsky.convo.getMessages";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    pub convo_id: String,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cursor: core::option::Option<String>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub limit: core::option::Option<crate::types::LimitedNonZeroU8<100u8>>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cursor: core::option::Option<String>,
    pub messages: Vec<crate::types::Union<OutputMessagesItem>>,
    ///Set of all members who authored or reacted to the returned messages. Members referred to by system messages are also included.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub related_profiles: core::option::Option<
        Vec<crate::chat::bsky::actor::defs::ProfileViewBasic>,
    >,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    InvalidConvo(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::InvalidConvo(msg) => {
                write!(_f, "InvalidConvo")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum OutputMessagesItem {
    #[serde(rename = "chat.bsky.convo.defs#messageView")]
    ChatBskyConvoDefsMessageView(Box<crate::chat::bsky::convo::defs::MessageView>),
    #[serde(rename = "chat.bsky.convo.defs#deletedMessageView")]
    ChatBskyConvoDefsDeletedMessageView(
        Box<crate::chat::bsky::convo::defs::DeletedMessageView>,
    ),
    #[serde(rename = "chat.bsky.convo.defs#systemMessageView")]
    ChatBskyConvoDefsSystemMessageView(
        Box<crate::chat::bsky::convo::defs::SystemMessageView>,
    ),
}
