// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `app.bsky.actor` namespace.
pub mod content_visibility_declaration;
pub mod defs;
pub mod get_preferences;
pub mod get_profile;
pub mod get_profiles;
pub mod get_suggestions;
pub mod profile;
pub mod put_preferences;
pub mod search_actors;
pub mod search_actors_typeahead;
pub mod status;
#[derive(Debug)]
pub struct ContentVisibilityDeclaration;
impl crate::types::Collection for ContentVisibilityDeclaration {
    const NSID: &'static str = "app.bsky.actor.contentVisibilityDeclaration";
    type Record = content_visibility_declaration::Record;
}
#[derive(Debug)]
pub struct Profile;
impl crate::types::Collection for Profile {
    const NSID: &'static str = "app.bsky.actor.profile";
    type Record = profile::Record;
}
#[derive(Debug)]
pub struct Status;
impl crate::types::Collection for Status {
    const NSID: &'static str = "app.bsky.actor.status";
    type Record = status::Record;
}
