// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `app.bsky.draft` namespace.
pub mod create_draft;
pub mod defs;
pub mod delete_draft;
pub mod get_drafts;
pub mod update_draft;
