// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `app.bsky.video` namespace.
pub mod abort_upload;
pub mod defs;
pub mod finish_upload;
pub mod get_job_status;
pub mod get_upload_limits;
pub mod get_upload_status;
pub mod start_upload;
pub mod upload_part;
pub mod upload_video;
