// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `chat.bsky.embed.joinLink` namespace.
//![NOTE: This is under active development and should be considered unstable while this note is here]. A join link embedded in a chat message.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct MainData {
    ///The join link code.
    pub code: String,
}
pub type Main = crate::types::Object<MainData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ViewData {
    pub join_link_preview: crate::types::Union<ViewJoinLinkPreviewRefs>,
}
pub type View = crate::types::Object<ViewData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum ViewJoinLinkPreviewRefs {
    #[serde(rename = "chat.bsky.group.defs#joinLinkPreviewView")]
    ChatBskyGroupDefsJoinLinkPreviewView(Box<crate::chat::bsky::group::defs::JoinLinkPreviewView>),
    #[serde(rename = "chat.bsky.group.defs#disabledJoinLinkPreviewView")]
    ChatBskyGroupDefsDisabledJoinLinkPreviewView(
        Box<crate::chat::bsky::group::defs::DisabledJoinLinkPreviewView>,
    ),
    #[serde(rename = "chat.bsky.group.defs#invalidJoinLinkPreviewView")]
    ChatBskyGroupDefsInvalidJoinLinkPreviewView(
        Box<crate::chat::bsky::group::defs::InvalidJoinLinkPreviewView>,
    ),
}
